### ISSUE TITLE
proposal: enable to deploy new service

### ISSUE THREAD

**Issue by kanata2** [kayac/ecspresso#175]
Thank you for great tool!

### Background
Being able to manage an existing app by a code base is very useful and easily, but on the other hand,
I often want to deploy new service from existing conf files with same tool (= ecspresso).

For example,  we have a situation where we want to create a dev, stg, prd env based on the conf files which we we have used in PoC env.

### Suggestion
I want to make `ecspresso deploy` enable the deployment of new services in addition to existing features.
Alternatively, this could be accomplished by passing a flag (such as `--new`) to `deploy` subcommand.

---

I apologize if it's already possible or if I've made suggestions that are outside of the ecspresso's philosophy.

**Comment by fujiwara** [comment]
An ecspresso config file can use syntaxes like `{{ env }}` and `{{ must_env }}`.

For example,

```yaml
region: ap-northeast-1
cluster: default
service: '{{ must_env `ECS_SERVICE` }}'
task_definition: myTask.json
```

How about switching the environment variable `ECS_SERVICE` for the deployment targets (dev, stg or prod)?
