### ISSUE TITLE
Specifying multiple tfstates

### ISSUE THREAD

**Issue by Liooo** [kayac/ecspresso#396]
Can we use values from multiple tfstate files?
I tried the following, but seems like only the last one is loaded.

```yml
# ecspresso.yml
...
plugins:
   - name: tfstate
    config:
      url: s3://tfstate1
  - name: tfstate
    config:
      url: s3://tfstate2
```

Thanks for the great tool.
