### ISSUE TITLE
Feature suggestion: SSM parameter store plugin

### ISSUE THREAD

**Issue by Liooo** [kayac/ecspresso#397]
Is there a plan to add plugin support for ssm parameter store? If not, are you willing to accept the PR if there's one?
I'm imagining something like below:

```yml
# ecspresso.yml

...
plugins:
  - name: ssm
```

```
# anywhere in ecs-service-def.json or task-def.json

{
   ...
   "some_key": "{{ ssm `/path/to/parameter` }}"
}
```

Thanks.
