### ISSUE TITLE
config file の service 定義不要で standalone task を実行できますか？

### ISSUE THREAD

**Issue by k-shiratoo** [kayac/ecspresso#405]
最近、ecspresso を使用し始めました！
理想的なツールだったので大変感謝しております😆
一点、気になる挙動がありましたので、確認したいです。

# 確認事項

* [standalone task](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_run_task.html) を実行する際に指定する config file から service の定義を削除することはできますか？
* 既存の service の情報を記述すると standalone task として動作します。
* しかし、standalone task は service 管理外での実行ため、 service の定義は不要かと思いました。

# version

$ ecspresso version  
ecspresso v1.7.7

# 現在の構成

## config file

```yaml:config.yaml
region: eu-west-3
cluster: test-cluster
service: test-service
service_definition: test-service.json
task_definition: test-task.json
timeout: 10m0s
```

## command

```console
$ ecspresso register --config ./config.yaml
$ ecspresso run --config ./config.yaml --latest-task-definition --skip-task-definition
```

# 理想の構成

## config file

```yaml:config.yaml
region: eu-west-3
cluster: test-cluster
task_definition: test-task.json
timeout: 10m0s
```

## command

* 同上
